name: Linux

on: [push]

jobs:
  test:
    strategy:
      matrix:
        config: [Release, Debug]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install PostgreSQL server headers
        run: |
          sudo apt update
          sudo apt-get install postgresql-server-dev-14 postgis

      - name: Configure PATH
        run: echo "$PGBIN" >> $GITHUB_PATH

      - name: Generate
        run: cmake -B build .

      - name: Build
        run: cmake --build build --config ${{ matrix.config }}

      - name: Install
        run: cmake --install build --config ${{ matrix.config }}

      - name: Test
        run: ctest --test-dir build --output-on-failure --build-config ${{ matrix.config }}
