name: CMake

on: [push]

jobs:
  windows:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        config: [Release, Debug]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure PATH
        run: echo "$PGBIN" >> $GITHUB_PATH

      - name: Generate
        run: cmake -B build .

      - name: Build
        run: cmake --build build --config ${{ matrix.config }}

      - name: Install
        run: cmake --install build --config ${{ matrix.config }}

      - name: Test
        run: ctest --test-dir build --output-on-failure --build-config ${{ matrix.config }}

defaults:
  run:
    shell: bash
