name: test-macos

on: [push]

jobs:
  macos:
    strategy:
      matrix:
        config: [Release, Debug]

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-2022

      #- name: Install pg_validate_extupgrade
      #  run: cargo install --locked --git https://github.com/rjuju/pg_validate_extupgrade.git

      - name: Generate
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build
        run: cmake --build build --config ${{ matrix.config }}

      - name: Install
        run: sudo cmake --install build --config ${{ matrix.config }}

      - name: Prepare PostgreSQL
        run: |
          brew services start postgresql@14

          echo "Check PostgreSQL service is running"
          i=20
          COMMAND='pg_isready'
          while [ $i -gt 0 ]; do
              echo "Check PostgreSQL service status"
              eval $COMMAND && break
              ((i--))
              if [ $i == 0 ]; then
                  echo "PostgreSQL service not ready, all attempts exhausted"
                  exit 1
              fi
              echo "PostgreSQL service not ready, wait 3 more sec, attempts left: $i"
              sleep 3
          done

          #createuser --superuser runner
          createdb runner

          psql -c 'SELECT 1;'
          psql -c 'SHOW data_directory;'

      - name: Test
        run: ctest --test-dir build --output-on-failure --build-config ${{ matrix.config }}

      - name: Print regression diffs
        if: ${{ failure() }}
        run: |
          cat /usr/local/var/log/postgres.log 2>/dev/null
          cat /usr/var/log/postgres.log 2>/dev/null
          cat build/*/regression.diffs 2>/dev/null
