name: test-macos

on: [push]

jobs:
  macos:
    strategy:
      matrix:
        config: [Release, Debug]

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Install pg_validate_extupgrade
        run: cargo install --locked --git https://github.com/rjuju/pg_validate_extupgrade.git

      - name: Generate
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build
        run: cmake --build build --config ${{ matrix.config }}

      - name: Install
        run: sudo cmake --install build --config ${{ matrix.config }}

      - name: Prepare PostgreSQL
        run: |
          brew services start postgresql
          # sudo -u postgres -i createuser --superuser runner
          # sudo -u postgres -i createdb runner

      - name: Test
        run: ctest --test-dir build --output-on-failure --build-config ${{ matrix.config }}
