name: test-windows

on: [push]

jobs:
  windows:
    strategy:
      matrix:
        config: [Release, Debug]

    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Configure PATH
        run: |
          "$env:PGBIN" >> $env:GITHUB_PATH

      - name: Generate
        run: cmake -B build .

      - name: Build
        run: cmake --build build --config ${{ matrix.config }}

      - name: Install
        run: cmake --install build --config ${{ matrix.config }}

      - name: Test
        run: ctest --test-dir build --output-on-failure --build-config ${{ matrix.config }}
